---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: qlik/gradle
    tag: latest

inputs:
- name: easy-config-server
- name: configserver-version

outputs:
- name: builds

run:
  path: easy-config-server/ci/build.sh